### ISSUE TITLE
Documentation regarding `BST`-Cases

### ISSUE THREAD

**Issue by goulashsoup** [arvidjaar/bootinfoscript#16]
https://github.com/arvidjaar/bootinfoscript/blob/71f6c5cb0d81bc74cca3d3af9e770357868b3029/bootinfoscript#L2595-L2600

I don't want to sound mistrusting but i think it would add credibility to add sources for the cases.
Unfortunately i couldn't found any info regarding these anywhere, probably because they are part of proprietary software etc...

@arvidjaar Where do these values come from? Did you tested the script with all listed systems?

Thanks in advance!

**Comment by arvidjaar** [comment]
> Where do these values come from? Did you tested the script with all listed systems?

No. They come from the original BIS from SF. You may try to see if there are any changelog, commit logs or may be mailing list posts.

**Comment by goulashsoup** [comment]
What does **BIS** and **SF** stand for?

**Comment by arvidjaar** [comment]
BootInfoScript and SourceForge
