### ISSUE TITLE
Bash < 4.2 does _not_ support negative values for substring expansion

### ISSUE THREAD

**Issue by 0rbiter** [arvidjaar/bootinfoscript#6]
Change line 3564 for POSIX compatibility to:
VM_Size=${LVM2_LV_SIZE%?};

instead of
VM_Size=${LVM2_LV_SIZE:0:-1}
This might work on bash < 4.2 when using MacOS but e.g. not on Bash 4.1.2(1) @ RHEL 6.8

### ASSUMING THIS IS INTENDED TO REMOVE THE LAST CHARACTER "S" from the LVM SIZE IN SECTORS ###

**Comment by arvidjaar** [comment]
Substring extraction appeared in bash 2.0; are you sure your problem is caused by it?

**Comment by 0rbiter** [comment]
negative values since 4.2...
Am 03.05.2017 19:06 schrieb "Andrei Borzenkov" <notifications@github.com>:

**Comment by arvidjaar** [comment]
Could you test https://github.com/arvidjaar/bootinfoscript/tree/issue/6 - I do not have LVM right now?

**Comment by 0rbiter** [comment]
tomorrow, yes.
Am 03.05.2017 19:51 schrieb "Andrei Borzenkov" <notifications@github.com>:
